// pages/searchFoods.js
import Head from "next/head";
import { useRouter } from "next/router";
import { withIronSessionSsr } from "iron-session/next";
import sessionOptions from "../config/session";
import styles from "../styles/searchFoods.module.css";
import Header from "../components/header";
import useLogout from "../hooks/useLogout";
import FoodSearch from "../components/FoodSearch"
import Image from "next/image";

export const getServerSideProps = withIronSessionSsr(
  async ({ req }) => {
    const user = req.session.user;

    if (!user) {
      return {
        redirect: {
          destination: "/login",
          permanent: false,
        },
      };
    }

    return {
      props: {
        user,
        isLoggedIn: true,
      },
    };
  },
  sessionOptions
);


export default function SearchFoods(props) {
  const router = useRouter();
  const logout = useLogout();
  return (
    <div className={styles.container}>
      <Head>
        <title>Search Foods</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header isLoggedIn={props.isLoggedIn} username={props?.user?.username} />

      <main className={styles.mainSearch}>
      <div className={styles.logoHead}>
        <img className={styles.logo2} src="/images/logoSearch.png" alt="A description of the image"></img>
          <h1 className={styles.title}>
            Search Foods 
          </h1>
       </div> 
       
        <h3>Enter the Name or Barcode</h3>
        <div><FoodSearch /></div>

      </main>

      
    </div>
  );
}
